spring.application.name=cadastro

## Spring DATASOURCE
# Verifique se o banco 'vendas_geral' já foi criado no seu PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vendas_geral

# Atenção: No PostgreSQL o padrão é 'postgres', não 'root'.
# Se você criou um usuário 'root', mantenha. Se não, use 'postgres'
spring.datasource.username=postgres
spring.datasource.password=123456

# Dialeto SQL CORRETO para PostgreSQL
# Dica: Nas versões novas do Spring Boot, você pode até APAGAR essa linha
# que o Hibernate descobre o dialeto sozinho.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto
spring.jpa.hibernate.ddl-auto=update

# Opcional: Adicione essa linha para ver os comandos SQL no console e facilitar o estudo
spring.jpa.show-sql=true